/**
 * ADMIN
 */
export const AUTH_ADMIN_PENDING = 'AUTH_ADMIN_PENDING';
export const ADMIN_AUTHED = 'ADMIN_AUTHED';
export const ERROR_IN_ADMIN_AUTH = 'ERROR_IN_ADMIN_AUTH';
export const ADMIN_LOGOUT = 'ADMIN_LOGOUT';

/**
 * TOURNAMENT
 */
export const FETCH_TOURNAMENT_INFO = 'FETCH_TOURNAMENT_INFO';
export const TOURNAMENT_INFO_FETCHED = 'TOURNAMENT_INFO_FETCHED';
export const TOURNAMENT_NOT_FOUND = 'TOURNAMENT_NOT_FOUND';
export const ERROR_IN_TOURNAMENT_INFO_FETCH = 'ERROR_IN_TOURNAMENT_INFO_FETCH';
export const CREATE_INFO_PENDING = 'CREATE_INFO_PENDING';
export const INFO_CREATED = 'INFO_CREATED';
export const ERROR_IN_INFO_CREATE = 'ERROR_IN_INFO_CREATE';
export const CREATE_TEAM_PENDING = 'CREATE_TEAM_PENDING';
export const TEAM_CREATED = 'TEAM_CREATED';
export const ERROR_IN_TEAM_CREATE = 'ERROR_IN_TEAM_CREATE';
export const FETCH_TOURNAMENT_TEAMS = 'FETCH_TOURNAMENT_TEAMS';
export const TOURNAMENT_TEAMS_FETCHED = 'TOURNAMENT_TEAMS_FETCHED';
export const ERROR_IN_TOURNAMENT_TEAMS_FETCH = 'ERROR_IN_TOURNAMENT_TEAMS_FETCH';
export const DELETE_TEAM_PENDING = 'DELETE_TEAM_PENDING';
export const TEAM_DELETED = 'TEAM_DELETED';
export const ERROR_IN_TEAM_DELETE = 'ERROR_IN_TEAM_DELETE';
export const EDIT_TEAM_PENDING = 'EDIT_TEAM_PENDING';
export const TEAM_EDITED = 'TEAM_EDITED';
export const ERROR_IN_TEAM_EDIT = 'ERROR_IN_TEAM_EDIT';
export const FETCH_TOURNAMENT_GROUPS = 'FETCH_TOURNAMENT_GROUPS';
export const TORUNAMENT_GROUPS_FETCHED = 'TORUNAMENT_GROUP_FETCHED';
export const ERROR_IN_TOURNAMENT_GROUPS_FETCH = 'ERROR_IN_TOURNAMENT_FETCH';
export const GENERATE_TOURNAMENT_GROUP_PENDING = 'GENERATE_TOURNAMENT_GROUP_PENDING';
export const TOURNAMENT_GROUP_GENERATED = 'TOURNAMENT_GROUP_GENERATED';
export const ERROR_IN_GENERATE_TOURNAMENT_GROUPS = 'ERROR_IN_GENERATE_TOURNAMENT_GROUPS';