/**
 * USER
 */
export const AUTH_ADMIN_PENDING = 'AUTH_ADMIN_PENDING';
export const ADMIN_AUTHED = 'ADMIN_AUTHED';
export const ERROR_IN_ADMIN_AUTH = 'ERROR_IN_ADMIN_AUTH';
export const ADMIN_LOGOUT = 'ADMIN_LOGOUT';

/**
 * TOURNAMENT
 */
export const FETCH_TOURNAMENT_INFO = 'FETCH_TOURNAMENT_INFO';
export const TOURNAMENT_INFO_FETCHED = 'TOURNAMENT_INFO_FETCHED';
export const ERROR_IN_TOURNAMENT_INFO_FETCH = 'ERROR_IN_TOURNAMENT_INFO_FETCH';